### ISSUE TITLE
Regarding data download

### ISSUE THREAD

**Issue by jayLEE0301** [pairlab/QueST#3]
Hello @atharvamete,
I appreciate your effort to release the codebase.

when I tired
```
python scripts/generate_metaworld_dataset.py
```

I found the error below

```
Available options in 'task':
        libero_90
        libero_base
        libero_long
        libero_long_fewshot
        metaworld_base
        metaworld_ml45_prise
        metaworld_ml45_prise_fewshot
```

so I changed `metaworld_ml45` to `metaworld_base` to solve this error, as shown below (in `collect_data.yaml`)
```yaml
defaults:
  - task: metaworld_base # originally metaworld_ml45
  - algo: data_collect
  - _self_
```  

however, even after changing this, I got another issue:

```
omegaconf.errors.InterpolationKeyError: Interpolation key 'task.n_tasks' not found
```

and I found that there's no `task.n_tasks` in `metaworld_base.yaml`

could you please give me some directions that I can solve this issue and download the dataset using `python scripts/generate_metaworld_dataset.py`?

thank you,
Seungjae.
